dist: trusty
os: linux

language: node_js
node_js: node

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: lint
      script:
        - npm run lint:all

    - stage: test
      script:
        - npm run test:all
        - npm run codecov

    - stage: e2e
      script:
        - npm run amds-app:e2e

    - stage: deploy
      script:
        - npm run amds-app:build
      deploy:
        provider: pages
        skip_cleanup: true
        edge: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/amds-app
        on:
          branch: master

    - stage: release
      script:
        - npm run amds-common:build
      before_deploy:
        - cd dist/amds-common
      deploy:
        provider: npm
        skip_cleanup: true
        edge: true
        email: 'diegoavieira@gmail.com'
        api_token: $NPM_TOKEN
        on:
          branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
