dist: trusty
os: linux

language: node_js
node_js: node

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm install

script:
  - npm run ci:amds-app

jobs:
  include:
    - stage: deploy github pages
      deploy:
        provider: pages
        skip_cleanup: true
        edge: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/amds-app
        on:
          branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
